Setup.cfg: pypdf requires version 3.10.0 or greater
Previous versions of pypdf will generate this error:
"TypeError: PdfWriter.update_page_form_field_values() got an unexpected keyword argument 'auto_regenerate'"