Fixed AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
This bug was introduced by commit https://github.com/BittyTax/BittyTax/commit/45b21005014d3483094b7a1d5f6910d4ad600c45.