Setup.cfg: added setuptools dependancy
Mypy was failing CI with the error:
src/bittytax/config.py:9: error: Library stubs not installed for "pkg_resources"  [import-untyped]

This was due to types-setuptools no longer typing pkg_resources as its been included in the main package since version 71.1.
See https://pypi.org/project/types-setuptools/75.8.2.20250305/.

Unfortunately older versions of Python were installed an older version of setuptools.