setup.py: workaround for xhtml2pdf issue with reportlab 3.6.7
The xhtml2pdf package is causing the exception below when using the latest reportlab 3.6.7 version:

File "/Library/Python/3.8/site-packages/xhtml2pdf/xhtml2pdf_reportlab.py", line 20, in
from reportlab.lib.utils import flatten, open_for_read, getStringIO,
ImportError: cannot import name 'getStringIO' from 'reportlab.lib.utils' (/Library/Python/3.8/site-packages/reportlab/lib/utils.py)

The workaround is to use 3.6.6 until xhtml2pdf is made compatible with 3.6.7.

This fixes #236.