Fixed AttributeError: 'AuditRecords' object has no attribute 'failures'
This bug was introduced in the static typing changes https://github.com/BittyTax/BittyTax/commit/03b018e017e5e2ffdbde9e60887956cc9e66c9f4.